name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install --user tox
        echo $PATH
        export PATH="/home/runner/.local/bin:$PATH"
    - name: Test with manage.py test
      run: |
        tox
