name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        which pip
        which pip3
        which python
        which python3
        python --version
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Test with manage.py test
      run: |
        pip3 install tox
        tox
